[package]
name = "example"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
<<<<<<< HEAD
description = "ArenaX Example Smart Contract"
=======
description = "Example Soroban contract for ArenaX"
>>>>>>> upstream/main

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk.workspace = true

[dev-dependencies]
<<<<<<< HEAD
soroban-sdk = { workspace = true, features = ["testutils"] }
=======
soroban-sdk = { workspace = true, features = ["testutils"] }
>>>>>>> upstream/main
